# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oentity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oentity.proto',
  package='org.csc.bcapi.gens',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\roentity.proto\x12\x12org.csc.bcapi.gens\"\x14\n\x04OKey\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"k\n\x06OValue\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x12\x10\n\x08\x64\x65\x63imals\x18\x02 \x01(\x05\x12\x0c\n\x04info\x18\x03 \x01(\t\x12\x0f\n\x07\x65xtdata\x18\x04 \x01(\x0c\x12\x12\n\nsecond_key\x18\x05 \x01(\t\x12\r\n\x05nonce\x18\x06 \x01(\x05\"Y\n\x05OPair\x12%\n\x03key\x18\x01 \x01(\x0b\x32\x18.org.csc.bcapi.gens.OKey\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.org.csc.bcapi.gens.OValue\"O\n\rKeyStoreValue\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05\x62\x63uid\x18\x02 \x01(\t\x12\x0e\n\x06prikey\x18\x03 \x01(\t\x12\x0e\n\x06pubkey\x18\x04 \x01(\tb\x06proto3')
)




_OKEY = _descriptor.Descriptor(
  name='OKey',
  full_name='org.csc.bcapi.gens.OKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='org.csc.bcapi.gens.OKey.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=57,
)


_OVALUE = _descriptor.Descriptor(
  name='OValue',
  full_name='org.csc.bcapi.gens.OValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='org.csc.bcapi.gens.OValue.count', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decimals', full_name='org.csc.bcapi.gens.OValue.decimals', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='org.csc.bcapi.gens.OValue.info', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extdata', full_name='org.csc.bcapi.gens.OValue.extdata', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='second_key', full_name='org.csc.bcapi.gens.OValue.second_key', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='org.csc.bcapi.gens.OValue.nonce', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=166,
)


_OPAIR = _descriptor.Descriptor(
  name='OPair',
  full_name='org.csc.bcapi.gens.OPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='org.csc.bcapi.gens.OPair.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='org.csc.bcapi.gens.OPair.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=257,
)


_KEYSTOREVALUE = _descriptor.Descriptor(
  name='KeyStoreValue',
  full_name='org.csc.bcapi.gens.KeyStoreValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='org.csc.bcapi.gens.KeyStoreValue.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bcuid', full_name='org.csc.bcapi.gens.KeyStoreValue.bcuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prikey', full_name='org.csc.bcapi.gens.KeyStoreValue.prikey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pubkey', full_name='org.csc.bcapi.gens.KeyStoreValue.pubkey', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=338,
)

_OPAIR.fields_by_name['key'].message_type = _OKEY
_OPAIR.fields_by_name['value'].message_type = _OVALUE
DESCRIPTOR.message_types_by_name['OKey'] = _OKEY
DESCRIPTOR.message_types_by_name['OValue'] = _OVALUE
DESCRIPTOR.message_types_by_name['OPair'] = _OPAIR
DESCRIPTOR.message_types_by_name['KeyStoreValue'] = _KEYSTOREVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OKey = _reflection.GeneratedProtocolMessageType('OKey', (_message.Message,), dict(
  DESCRIPTOR = _OKEY,
  __module__ = 'oentity_pb2'
  # @@protoc_insertion_point(class_scope:org.csc.bcapi.gens.OKey)
  ))
_sym_db.RegisterMessage(OKey)

OValue = _reflection.GeneratedProtocolMessageType('OValue', (_message.Message,), dict(
  DESCRIPTOR = _OVALUE,
  __module__ = 'oentity_pb2'
  # @@protoc_insertion_point(class_scope:org.csc.bcapi.gens.OValue)
  ))
_sym_db.RegisterMessage(OValue)

OPair = _reflection.GeneratedProtocolMessageType('OPair', (_message.Message,), dict(
  DESCRIPTOR = _OPAIR,
  __module__ = 'oentity_pb2'
  # @@protoc_insertion_point(class_scope:org.csc.bcapi.gens.OPair)
  ))
_sym_db.RegisterMessage(OPair)

KeyStoreValue = _reflection.GeneratedProtocolMessageType('KeyStoreValue', (_message.Message,), dict(
  DESCRIPTOR = _KEYSTOREVALUE,
  __module__ = 'oentity_pb2'
  # @@protoc_insertion_point(class_scope:org.csc.bcapi.gens.KeyStoreValue)
  ))
_sym_db.RegisterMessage(KeyStoreValue)


# @@protoc_insertion_point(module_scope)
